import turtle
fred = turtle.Pen()
fred.shape("turtle")
fred.forward(100)
fred.left(90)
fred.forward(100)
fred.left(90)
fred.forward(100)
fred.left(90)
fred.forward(100)
fred.reset()
fred.color("red")
fred.forward(100)
fred.circle(100)
fred.circle(-100)
fred.reset()
fred.color("blue")
fred.forward(100)
fred.up()
fred.forward(100)
fred.down()
fred.circle(50)
fred.forward(100)
